export const cards = [
    {
        id: '1',
        new: false,
        image: 'https://i.picsum.photos/id/455/200/200.jpg?hmac=YZhCbBjCYF0ha5dR9ElToDVwWcw05w0e4pAv5S9nZYg',
        title: 'Чикен Сладкий Чили',
        body: 'Курица, Лук, Перец Халапеньо, Сыр Моцарелла, Томатный соу...',
        type: 'pizza',
        price: 399,
        count: 1,
    },
    {
        id: '2',
        new: false,
        image: 'https://i.picsum.photos/id/455/200/200.jpg?hmac=YZhCbBjCYF0ha5dR9ElToDVwWcw05w0e4pAv5S9nZYg',
        title: 'EASY PEASY огуречный расколбас',
        body: 'Курица, Лук, Перец Халапеньо...',
        type: 'pizza',
        price: 549,
        count: 1,
    },
    {
        id: '3',
        new: false,
        image: 'https://i.picsum.photos/id/455/200/200.jpg?hmac=YZhCbBjCYF0ha5dR9ElToDVwWcw05w0e4pAv5S9nZYg',
        title: 'EASY PEASY чикен а-ля хрен',
        body: 'Курица, Лук, Соус Карбонара,...',
        type: 'pizza',
        price: 249,
        count: 1,
    },
    {
        id: '4',
        new: false,
        image: 'https://i.picsum.photos/id/455/200/200.jpg?hmac=YZhCbBjCYF0ha5dR9ElToDVwWcw05w0e4pAv5S9nZYg',
        title: '4 сезона',
        body: 'Бекон, Ветчина, Грибы, Курица, Лук, Маслины, Огурцы мари...',
        type: 'pizza',
        price: 630,
        count: 1,
    },
]

export const sushi = [
    {
        id: '5',
        new: false,
        image: 'https://i.picsum.photos/id/351/200/300.jpg?hmac=OSQYmRI8IZkaMcC4ERotpBhe0AymVYajIIKPJFDzGBY',
        title: 'Филадельфия кранч',
        body: 'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
        type: 'sushi',
        price: 475,
        count: 1,
    },
    {
        id: '6',
        new: false,
        image: 'https://i.picsum.photos/id/351/200/300.jpg?hmac=OSQYmRI8IZkaMcC4ERotpBhe0AymVYajIIKPJFDzGBY',
        title: 'Филадельфия крем-брюле',
        body: 'Сливочный сыр, семга татаки с тростниковым сахаром, соус у...',
        type: 'sushi',
        price: 395,
        count: 1,
    },
    {
        id: '7',
        new: false,
        image: 'https://i.picsum.photos/id/351/200/300.jpg?hmac=OSQYmRI8IZkaMcC4ERotpBhe0AymVYajIIKPJFDzGBY',
        title: 'Супер Филадельфия',
        body: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
        type: 'sushi',
        price: 425,
        count: 1,
    },
    {
        id: '8',
        new: false,
        image: 'https://i.picsum.photos/id/351/200/300.jpg?hmac=OSQYmRI8IZkaMcC4ERotpBhe0AymVYajIIKPJFDzGBY',
        title: 'Тигр мама',
        body: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
        type: 'sushi',
        price: 525,
        count: 1,
    },
]

export const snacks = [
    {
        id: '9',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Филадельфия кранч',
        body: 'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
        type: 'snacks',
        price: 475,
        count: 1,
    },
    {
        id: '10',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Филадельфия крем-брюле',
        body: 'Сливочный сыр, семга татаки с тростниковым сахаром, соус у...',
        type: 'snacks',
        price: 395,
        count: 1,
    },
    {
        id: '11',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Супер Филадельфия',
        body: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
        type: 'snacks',
        price: 425,
        count: 1,
    },
    {
        id: '12',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Тигр мама',
        body: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
        type: 'snacks',
        price: 525,
        count: 1,
    },
]

export const desserts = [
    {
        id: '13',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Филадельфия кранч',
        body: 'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
        type: 'sauces',
        price: 475,
        count: 1,
    },
    {
        id: '14',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Филадельфия крем-брюле',
        body: 'Сливочный сыр, семга татаки с тростниковым сахаром, соус у...',
        type: 'sauces',
        price: 395,
        count: 1,
    },
    {
        id: '15',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Супер Филадельфия',
        body: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
        type: 'sauces',
        price: 425,
        count: 1,
    },
    {
        id: '16',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Тигр мама',
        body: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
        type: 'sauces',
        price: 525,
        count: 1,
    },
]

export const sauces = [
    {
        id: '17',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Филадельфия кранч',
        body: 'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
        type: 'desserts',
        price: 475,
        count: 1,
    },
    {
        id: '18',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Филадельфия крем-брюле',
        body: 'Сливочный сыр, семга татаки с тростниковым сахаром, соус у...',
        type: 'desserts',
        price: 395,
        count: 1,
    },
    {
        id: '19',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Супер Филадельфия',
        body: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
        type: 'desserts',
        price: 425,
        count: 1,
    },
    {
        id: '20',
        new: false,
        image: 'https://i.picsum.photos/id/537/200/300.jpg?hmac=LG3kZs5AdrMmsgeVOdrfP0C5KT3WmP-q5TauEZdR4vk',
        title: 'Тигр мама',
        body: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
        type: 'desserts',
        price: 525,
        count: 1,
    },
]
